[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.15.4",
  "pnpm install --no-frozen-lockfile --filter @pedizi/api..."
]

[phases.build]
cmds = [
  "pnpm --filter @pedizi/api exec prisma generate",
  "pnpm --filter @pedizi/api build"
]

[start]
cmd = "node apps/api/dist/main"
